version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realtordb
    ports:
      - "5432:5432"
    volumes:
      - db_data_realtor
      :/var/lib/postgresql/data
volumes:
  db_data_realtor: